name: Self-Hosted Analysis

on:
  push:
    branches: [ main, copilot/* ]
  pull_request:
    branches: [ main ]

jobs:
  analysis:
    name: Static Analysis
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Test Python and PowerShell
      shell: pwsh
      run: |
        Write-Host "=== Environment Check ==="
        Write-Host "Working Directory: $(Get-Location)"
        Write-Host "Python version:"
        python --version
        Write-Host "PowerShell version: $($PSVersionTable.PSVersion)"
        Write-Host "Files in current directory:"
        Get-ChildItem -Name
    
    - name: Generate compile commands
      shell: pwsh
      run: |
        Write-Host "Generating compile commands..."
        python generate_compile_commands.py
    
    - name: Run Ultimate Analysis
      shell: pwsh
      run: |
        Write-Host "Running ultimate analysis..."
        .\run-ultimate-analysis.ps1 -FixableOnly
    
    - name: Upload results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: analysis-results
        path: analysis-reports/